apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: passion-mansour-teambeam-frontend
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: passion-mansour-teambeam-frontend
              servicePort: 3000
              path: /
              pathType: Prefix
