name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Set up Git
        run: |
          git config --global kimsudang 'github-actions[bot]'
          git config --global 0ksuyeon0@gmail.com 'github-actions[bot]@users.noreply.github.com'

      - name: Push to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SUYEON_GITHUB_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'kimsudang'
          destination-repository-name: 'passion-mansour-teambeam-frontend'
          user-email: ${{ secrets.SUYEON_ACCOUNT_EMAIL }}
          commit-message: "Automated commit from GitHub Actions"
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
